version: "2.2"
services:

  leave-ms:
    container_name: leave-ms
    build:
      context: ./LeaveMS
      dockerfile: Dockerfile
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/leavemsdb?createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8085:8085"
    depends_on:
      - mysql-db
      - gateway
      - eureka-server
  user-ms:
    container_name: user-ms
    build:
      context: ./UserMS
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db-1:3306/users?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
      - gateway
      - eureka-server

  event-ms:
    container_name: event-ms
    build:
      context: ./EventMS
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - h2-db
      - gateway
      - eureka-server
  team-ms:
    container_name: team-ms
    build:
      context: ./TeamMS
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-db:5432/TeamDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=saif9782536
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://elastic_boyd:8080/realms/leave_ms
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://elastic_boyd:8080/realms/leave_ms/protocol/openid-connect/certs
      - jwt.auth.converter.resource-id=leave-rest-api
      - jwt.auth.converter.principle-attribute=preferred_username
    ports:
      - "8088:8088"
    depends_on:
      - postgresql-db
      - gateway
      - eureka-server
  eureka-server:
    container_name: eureka-server
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - h2-db
  mysql-db:
    container_name: mysql-db
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: leavemsdb
  mysql-db-1:
    container_name: mysql-db-1
    image: mysql:5.6
    ports:
      - "3304:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: users
  h2-db:
    container_name: h2-db
    image: openjdk:17
    ports:
      - "8084:8084"
    environment:
      - SPRING_H2_CONSOLE_ENABLED=true
  postgresql-db:
    container_name: postgresql-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saif9782536
      POSTGRES_DB: TeamDB
  gateway:
    container_name: gateway
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@eureka-server:8761/eureka/
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://elastic_boyd:8080/realms/leave_ms
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://elastic_boyd:8080/realms/leave_ms/protocol/openid-connect/certs
      - jwt.auth.converter.resource-id=leave-rest-api
      - jwt.auth.converter.principle-attribute=preferred_username
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server